### ISSUE TITLE
Make load_city() work with CityJSON

### ISSUE THREAD

**Issue by anderslogg** [dtcc-platform/dtcc-io#19]
I expect the following to work:

    city = load_city("DenHaag_01.city.json")
    
Now gives the following error message:

    $ python quantities.py 
    2024-02-19 09:59:42,640 [dtcc-io] [INFO] Loading city (City) from DenHaag_01.city.json
    2024-02-19 09:59:42,655 [fiona._env] [ERROR] `DenHaag_01.city.json' not recognized as a supported file format.
    Traceback (most recent call last):
      File "fiona/ogrext.pyx", line 136, in fiona.ogrext.gdal_open_vector
      File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer
    fiona._err.CPLE_OpenFailedError: 'DenHaag_01.city.json' not recognized as a supported file format.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/dtcc_io/city.py", line 98, in _load_fiona
        f = fiona.open(filename)
            ^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/fiona/env.py", line 457, in wrapper
        return f(*args, **kwds)
               ^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/fiona/__init__.py", line 292, in open
        colxn = Collection(
                ^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/fiona/collection.py", line 243, in __init__
        self.session.start(self, **kwargs)
      File "fiona/ogrext.pyx", line 588, in fiona.ogrext.Session.start
      File "fiona/ogrext.pyx", line 143, in fiona.ogrext.gdal_open_vector
    fiona.errors.DriverError: 'DenHaag_01.city.json' not recognized as a supported file format.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/logg/scratch/dtcc/dtcc/sandbox/quantities.py", line 6, in <module>
        city = load_city("DenHaag_01.city.json")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/dtcc_io/city.py", line 193, in load
        return generic.load(
               ^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/dtcc_io/generic.py", line 27, in load
        return formats[type][path.suffix](path, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/dtcc_io/city.py", line 101, in _load_fiona
        raise ValueError(f"File {filename} is not a valid file format")
    ValueError: File DenHaag_01.city.json is not a valid file format

**Comment by vbassn** [comment]
its in the new_data_model branch
